# Generated by Django 3.2.9 on 2021-11-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100, verbose_name='Job Title')),
                ('lastDateOfApply', models.DateField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('level', models.CharField(max_length=255, null=True)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10, verbose_name='Shift')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('vacancies', models.IntegerField()),
                ('jobDescription', models.TextField(null=True)),
                ('uploadCV', models.FileField(upload_to='user/')),
            ],
        ),
        migrations.CreateModel(
            name='UserJobAppliedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='RecruitmentManagementApp.jobpostmodel')),
            ],
        ),
    ]
