# Generated by Django 3.2.9 on 2021-12-28 12:00

import RecruitmentManagementApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sscCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('hscCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('graduationCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('postGraduationCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('nidCard', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('userPassportImage', models.ImageField(blank=True, upload_to=RecruitmentManagementApp.models.image_file_name)),
                ('passportSizePhoto', models.ImageField(blank=True, upload_to=RecruitmentManagementApp.models.image_file_name)),
                ('digitalSignature', models.ImageField(blank=True, upload_to=RecruitmentManagementApp.models.image_file_name)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FilterQuestionsResponseModelHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100, verbose_name='Job Title')),
                ('lastDateOfApply', models.DateField()),
                ('postDate', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10, verbose_name='Shift')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('vacancies', models.IntegerField()),
                ('jobType', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('internship', 'Internship')], max_length=50, verbose_name='job type')),
                ('jobDescription', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('statusOrder', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=256, verbose_name='Test Name')),
                ('test_link', models.URLField(verbose_name='Test Link')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTestResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=200)),
                ('testMark', models.IntegerField(blank=True, verbose_name='Test Mark')),
                ('testScnSrt', models.ImageField(blank=True, default='users/default.png', upload_to='online_test/test_res/', verbose_name='Screenshot')),
                ('submittedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalFile', models.FileField(upload_to='users/files', verbose_name='Practical Test File')),
                ('testLink', models.URLField(blank=True, verbose_name='Test link')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTestResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalTestResFiles', models.FileField(blank=True, upload_to='practical_test/response/', verbose_name='Practical test response')),
                ('practicalTestResLink', models.URLField(blank=True, verbose_name='Practical test response')),
                ('submittedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('relationWithReferer', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('attachedFile', models.FileField(blank=True, null=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobAppliedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedDate', models.DateTimeField(auto_now=True)),
                ('jobPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_post_id', to='RecruitmentManagementApp.jobpostmodel')),
                ('jobProgressStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_progress_status', to='RecruitmentManagementApp.jobstatusmodel')),
            ],
        ),
    ]
