# Generated by Django 3.2.9 on 2021-12-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterQuestionsResponseModelHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100, verbose_name='Job Title')),
                ('lastDateOfApply', models.DateField()),
                ('postDate', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10, verbose_name='Shift')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('vacancies', models.IntegerField()),
                ('jobType', models.CharField(choices=[('pert_time', 'Pert Time'), ('full_time', 'Full Time'), ('internship', 'Internship')], max_length=50, verbose_name='job type')),
                ('jobDescription', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('statusOrder', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultural_test', models.URLField(verbose_name='Cultural Test')),
                ('analytical_test', models.URLField(verbose_name='Analytical Test')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTestResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyticalTestMark', models.IntegerField(blank=True, verbose_name='Analytical Test Mark')),
                ('analyticalTestScnSrt', models.ImageField(blank=True, upload_to='online_test/analytical_test/', verbose_name='Screenshot')),
                ('practicalTestMark', models.IntegerField(blank=True, verbose_name='Practical Test Mark')),
                ('practicalTestScnSrt', models.ImageField(blank=True, upload_to='online_test/practical_test/', verbose_name='Screenshot')),
                ('submittedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalFile', models.FileField(upload_to='users/files', verbose_name='Practical Test File')),
                ('testLink', models.URLField(blank=True, verbose_name='Test link')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTestResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalTestResFiles', models.FileField(blank=True, upload_to='practical_test/response/')),
                ('practicalTestResLink', models.URLField(blank=True)),
                ('submittedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobAppliedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedDate', models.DateTimeField(auto_now=True)),
                ('jobPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_post_id', to='RecruitmentManagementApp.jobpostmodel')),
                ('jobProgressStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_progress_status', to='RecruitmentManagementApp.jobstatusmodel')),
            ],
        ),
    ]
