# Generated by Django 3.2.9 on 2021-11-22 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0001_initial'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobappliedmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_jobPost', to='UserApp.userdepartmentmodel'),
        ),
    ]
