# Generated by Django 3.2.9 on 2022-01-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterquestionsresponsemodelhr',
            name='jobPost',
        ),
        migrations.AddField(
            model_name='filterquestionsresponsemodelhr',
            name='appliedJob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter_question_job_application', to='RecruitmentManagementApp.userjobappliedmodel'),
            preserve_default=False,
        ),
    ]
