# Generated by Django 3.2.9 on 2022-01-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0003_auto_20220107_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterquestionsresponsemodelhr',
            name='appliedJob',
        ),
        migrations.AddField(
            model_name='filterquestionsresponsemodelhr',
            name='jobPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_info', to='RecruitmentManagementApp.jobpostmodel'),
            preserve_default=False,
        ),
    ]
