# Generated by Django 3.2.9 on 2021-12-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0003_jobpostmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='uploadCV',
        ),
    ]
