# Generated by Django 3.2.9 on 2022-02-01 06:23

import RecruitmentManagementApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0004_auto_20220107_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentLetter', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='RecruitmentManagementApp.userjobappliedmodel')),
            ],
        ),
    ]
