# Generated by Django 3.2.9 on 2021-12-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0004_auto_20211220_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaltestresponsemodel',
            name='practicalTestResFiles',
            field=models.FileField(blank=True, upload_to='practical_test/response/', verbose_name='Practical test response'),
        ),
        migrations.AlterField(
            model_name='practicaltestresponsemodel',
            name='practicalTestResLink',
            field=models.URLField(blank=True, verbose_name='Practical test response'),
        ),
    ]
