# Generated by Django 3.2.9 on 2021-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0004_remove_jobpostmodel_uploadcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='jobType',
            field=models.CharField(choices=[('per_time', 'Per Time'), ('full_time', 'Full Time'), ('internship', 'Internship')], default=1, max_length=50, verbose_name='job type'),
            preserve_default=False,
        ),
    ]
