# Generated by Django 3.2.9 on 2022-02-02 05:54

import RecruitmentManagementApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0005_officialdocumentsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentsmodel',
            name='appointmentLetter',
            field=models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.appointment_file_name),
        ),
    ]
