# Generated by Django 3.2.9 on 2021-12-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0005_auto_20211220_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaltestresponsemodel',
            name='appliedJob',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_practical_response', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
