# Generated by Django 3.2.9 on 2021-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0020_filterquestionsresponsemodel_user'),
        ('RecruitmentManagementApp', '0005_jobpostmodel_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='filterQuestions',
            field=models.ManyToManyField(related_name='filter_question_list', to='QuizApp.JobApplyFilterQuestionModel'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='jobType',
            field=models.CharField(choices=[('pert_time', 'Pert Time'), ('full_time', 'Full Time'), ('internship', 'Internship')], max_length=50, verbose_name='job type'),
        ),
    ]
