# Generated by Django 3.2.9 on 2022-02-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0006_alter_officialdocumentsmodel_appointmentletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentsmodel',
            name='applicationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AlterField(
            model_name='officialdocumentsmodel',
            name='appointmentLetter',
            field=models.TextField(),
        ),
    ]
