# Generated by Django 3.2.9 on 2021-12-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0006_alter_practicaltestresponsemodel_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='jobProgressStatus',
            field=models.ManyToManyField(related_name='job_progress_statusM2M', to='RecruitmentManagementApp.JobStatusModel'),
        ),
    ]
