# Generated by Django 3.2.9 on 2021-12-05 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0007_filterquestionsresponsemodelhr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='startDate',
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='postDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PracticalTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalQuestion', models.FileField(upload_to='users/files', verbose_name='Practical Question')),
                ('jobInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_info_practical', to='RecruitmentManagementApp.jobpostmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultural_test', models.URLField(verbose_name='Cultural Test')),
                ('analytical_test', models.URLField(verbose_name='Analytical Test')),
                ('jobInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_info_online', to='RecruitmentManagementApp.jobpostmodel')),
            ],
        ),
    ]
