# Generated by Django 3.2.9 on 2021-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0007_jobpostmodel_jobprogressstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinetestmodel',
            name='analytical_test',
        ),
        migrations.RemoveField(
            model_name='onlinetestmodel',
            name='cultural_test',
        ),
        migrations.AddField(
            model_name='onlinetestmodel',
            name='test_link',
            field=models.URLField(default=1, verbose_name='Test Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinetestmodel',
            name='test_name',
            field=models.CharField(default=1, max_length=256, verbose_name='Test Name'),
            preserve_default=False,
        ),
    ]
