# Generated by Django 3.2.9 on 2022-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0007_auto_20220203_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceinformationmodel',
            name='refVerified',
            field=models.BooleanField(default=False),
        ),
    ]
