# Generated by Django 3.2.9 on 2022-02-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0008_referenceinformationmodel_refverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenceinformationmodel',
            old_name='refVerified',
            new_name='is_verified',
        ),
    ]
