# Generated by Django 3.2.9 on 2021-12-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0008_auto_20211205_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetestmodel',
            old_name='jobInfo',
            new_name='jobInfoOnline',
        ),
    ]
