# Generated by Django 3.2.9 on 2021-12-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0008_auto_20211220_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetestmodel',
            name='jobInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_info_online', to='RecruitmentManagementApp.jobpostmodel'),
        ),
    ]
