# Generated by Django 3.2.9 on 2021-12-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0009_rename_jobinfo_onlinetestmodel_jobinfoonline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetestmodel',
            old_name='jobInfoOnline',
            new_name='jobInfo',
        ),
    ]
