# Generated by Django 3.2.9 on 2021-12-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0009_alter_onlinetestmodel_jobinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetestresponsemodel',
            old_name='analyticalTestMark',
            new_name='TestMark',
        ),
        migrations.RenameField(
            model_name='onlinetestresponsemodel',
            old_name='analyticalTestScnSrt',
            new_name='TestScnSrt',
        ),
        migrations.RemoveField(
            model_name='onlinetestresponsemodel',
            name='practicalTestMark',
        ),
        migrations.RemoveField(
            model_name='onlinetestresponsemodel',
            name='practicalTestScnSrt',
        ),
        migrations.AddField(
            model_name='onlinetestresponsemodel',
            name='testName',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='test_name_online_test', to='RecruitmentManagementApp.onlinetestmodel'),
            preserve_default=False,
        ),
    ]
