# Generated by Django 3.2.9 on 2022-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0010_referenceinformationmodel_callrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceinformationmodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
