# Generated by Django 3.2.9 on 2021-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0010_rename_jobinfoonline_onlinetestmodel_jobinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTestResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyticalTestMark', models.IntegerField(blank=True)),
                ('analyticalTestScnSrt', models.ImageField(blank=True, upload_to='online_test/analytical_test/')),
                ('practicalTestMark', models.IntegerField(blank=True)),
                ('practicalTestScnSrt', models.ImageField(blank=True, upload_to='online_test/practical_test/')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalTestResFiles', models.FileField(blank=True, upload_to='practical_test/response/')),
                ('practicalTestResLink', models.URLField(blank=True)),
            ],
        ),
    ]
