# Generated by Django 3.2.9 on 2021-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0011_alter_onlinetestresponsemodel_testname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='testName',
            field=models.CharField(max_length=200),
        ),
    ]
