# Generated by Django 3.2.9 on 2021-12-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0011_onlinetestresponsemodel_practicaltestresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticalTestResponse',
            new_name='PracticalTestResponseModel',
        ),
    ]
