# Generated by Django 3.2.9 on 2022-02-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0011_referenceinformationmodel_is_sent'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='jobpostmodel',
    #         name='filterQuestions',
    #     ),
    # ]
