# Generated by Django 3.2.9 on 2021-12-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0012_alter_onlinetestresponsemodel_testname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='appliedJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_online_response', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
