# Generated by Django 3.2.9 on 2022-02-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20220207_1303'),
        ('RecruitmentManagementApp', '0012_remove_jobpostmodel_filterquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldType', models.CharField(max_length=50, verbose_name='Field Type')),
            ],
            options={
                'verbose_name_plural': 'Field Type',
            },
        ),
        migrations.CreateModel(
            name='JobApplyFilterQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='filter_question')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_department_name', to='UserApp.userdepartmentmodel')),
                ('fieldType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_question_field_type', to='RecruitmentManagementApp.fieldtypemodels')),
            ],
            options={
                'verbose_name_plural': 'Filter Question List',
            },
        ),
        migrations.CreateModel(
            name='FilterQuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_apply_filter_question_answer', to='RecruitmentManagementApp.jobapplyfilterquestionmodel')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='filterquestionsresponsemodelhr',
        #     name='questions',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_questions', to='RecruitmentManagementApp.jobapplyfilterquestionmodel'),
        # ),
    ]
