# Generated by Django 3.2.9 on 2021-12-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0013_alter_onlinetestresponsemodel_appliedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinetestresponsemodel',
            old_name='TestMark',
            new_name='testMark',
        ),
        migrations.RenameField(
            model_name='onlinetestresponsemodel',
            old_name='TestScnSrt',
            new_name='testScnSrt',
        ),
    ]
