# Generated by Django 3.2.9 on 2022-02-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0013_auto_20220207_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplyfilterquestionmodel',
            name='department',
        ),
        migrations.AddField(
            model_name='jobapplyfilterquestionmodel',
            name='jobId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filter_qus_job_info', to='RecruitmentManagementApp.jobpostmodel'),
            preserve_default=False,
        ),
    ]
