# Generated by Django 3.2.9 on 2021-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0014_auto_20211220_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='testScnSrt',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='online_test/analytical_test/', verbose_name='Screenshot'),
        ),
    ]
