# Generated by Django 3.2.9 on 2021-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0015_alter_onlinetestresponsemodel_testscnsrt'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatusmodel',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jobstatusmodel',
            name='statusOrder',
            field=models.IntegerField(),
        ),
    ]
