# Generated by Django 3.2.9 on 2022-02-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0015_alter_practicaltestmodel_practicalfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('roster', 'Roster')], max_length=10, verbose_name='Shift'),
        ),
    ]
