# Generated by Django 3.2.9 on 2021-12-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0015_alter_userjobappliedmodel_jobprogressstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetestresponsemodel',
            name='jobId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='online_response_job', to='RecruitmentManagementApp.jobpostmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinetestresponsemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='online_response_user', to='UserApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaltestresponsemodel',
            name='jobId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practical_response_job', to='RecruitmentManagementApp.jobpostmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaltestresponsemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practical_response_user', to='UserApp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='jobProgressStatus',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('online', 'online'), ('under_review', 'under_review'), ('selected_for_practical', 'selected_for_practical'), ('under_review', 'under_review'), ('interview', 'interview'), ('document', 'document'), ('verification', 'verification'), ('appointed', 'appointed')], max_length=30),
        ),
    ]
