# Generated by Django 3.2.9 on 2021-12-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0016_auto_20211221_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatusmodel',
            name='is_completed',
        ),
    ]
