# Generated by Django 3.2.9 on 2021-12-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0016_auto_20211206_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltestmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practical_user_info', to='UserApp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='analyticalTestMark',
            field=models.IntegerField(blank=True, verbose_name='Analytical Test Mark'),
        ),
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='analyticalTestScnSrt',
            field=models.ImageField(blank=True, upload_to='online_test/analytical_test/', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='practicalTestMark',
            field=models.IntegerField(blank=True, verbose_name='Practical Test Mark'),
        ),
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='practicalTestScnSrt',
            field=models.ImageField(blank=True, upload_to='online_test/practical_test/', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='practicaltestmodel',
            name='jobInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_job_info', to='RecruitmentManagementApp.jobpostmodel'),
        ),
    ]
