# Generated by Django 3.2.9 on 2022-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0016_alter_jobpostmodel_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaltestresponsemodel',
            name='practicalTestResLink',
            field=models.CharField(blank=True, max_length=255, verbose_name='Practical test response'),
        ),
    ]
