# Generated by Django 3.2.9 on 2021-12-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0017_remove_jobstatusmodel_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='testMark',
            field=models.IntegerField(blank=True, verbose_name='Test Mark'),
        ),
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='testScnSrt',
            field=models.ImageField(blank=True, default='users/default.png', upload_to='online_test/test_res/', verbose_name='Screenshot'),
        ),
    ]
