# Generated by Django 3.2.9 on 2021-12-26 10:43

import RecruitmentManagementApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0018_auto_20211226_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('relationWithReferer', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('attachedFile', models.FileField(blank=True, null=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('applied_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='references_submission_applied_job', to='RecruitmentManagementApp.userjobappliedmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_information_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sscCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('hscCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('graduationCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('postGraduationCertificate', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('nidCard', models.FileField(blank=True, upload_to=RecruitmentManagementApp.models.content_file_name)),
                ('userPassportImage', models.ImageField(blank=True, upload_to=RecruitmentManagementApp.models.image_file_name)),
                ('passportSizePhoto', models.ImageField(blank=True, upload_to=RecruitmentManagementApp.models.image_file_name)),
                ('digitalSignature', models.ImageField(blank=True, upload_to=RecruitmentManagementApp.models.image_file_name)),
                ('is_verified', models.BooleanField(default=False)),
                ('applied_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_submission_applied_job', to='RecruitmentManagementApp.userjobappliedmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
