# Generated by Django 3.2.9 on 2021-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0018_auto_20211207_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='jobProgressStatus',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('online', 'online'), ('under_review', 'under_review'), ('selected_for_practical', 'selected_for_practical'), ('under_review', 'under_review'), ('interview', 'interview'), ('document', 'document'), ('verification', 'verification'), ('appointed', 'appointed'), ('rejected', 'rejected')], max_length=30),
        ),
    ]
