# Generated by Django 3.2.9 on 2022-03-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0018_auto_20220224_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFilterQuestionRadioButtonOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=255)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_question_option_job', to='RecruitmentManagementApp.jobpostmodel')),
            ],
        ),
    ]
