# Generated by Django 3.2.9 on 2021-12-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0019_documentsubmissionmodel_referenceinformationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='applied_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_submission_applied_job', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
