# Generated by Django 3.2.9 on 2021-12-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0019_alter_userjobappliedmodel_jobprogressstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinetestresponsemodel',
            name='appliedJob',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_online_response', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='jobProgressStatus',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('online', 'online'), ('under_review', 'under_review'), ('selected_for_practical', 'selected_for_practical'), ('test_under_review', 'test_under_review'), ('interview', 'interview'), ('document', 'document'), ('verification', 'verification'), ('appointed', 'appointed'), ('rejected', 'rejected')], max_length=30),
        ),
    ]
