# Generated by Django 3.2.9 on 2021-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0020_auto_20211208_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetestresponsemodel',
            name='submittedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='practicaltestresponsemodel',
            name='submittedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userjobappliedmodel',
            name='appliedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='jobProgressStatus',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('online', 'online'), ('under_review', 'under_review'), ('selected_for_practical', 'selected_for_practical'), ('test_under_review', 'test_under_review'), ('interview', 'interview'), ('document', 'document'), ('reference', 'reference'), ('verification', 'verification'), ('appointed', 'appointed'), ('rejected', 'rejected')], max_length=30),
        ),
    ]
