# Generated by Django 3.2.9 on 2021-12-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0021_auto_20211209_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicaltestmodel',
            name='practicalQuestion',
        ),
        migrations.AddField(
            model_name='practicaltestmodel',
            name='practicalFile',
            field=models.FileField(default=1, upload_to='users/files', verbose_name='Practical Test File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaltestmodel',
            name='testLink',
            field=models.URLField(blank=True, verbose_name='Test link'),
        ),
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='jobProgressStatus',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('online', 'online'), ('under_review', 'under_review'), ('practical', 'practical'), ('test_under_review', 'test_under_review'), ('interview', 'interview'), ('document', 'document'), ('reference', 'reference'), ('verification', 'verification'), ('appointed', 'appointed'), ('rejected', 'rejected')], max_length=30),
        ),
    ]
