# Generated by Django 3.2.9 on 2022-03-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0021_alter_jobfilterquestionradiobuttonoptionmodel_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplyfilterquestionmodel',
            name='fieldType',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Radio'), (3, 'Custom')], max_length=50),
        ),
        migrations.DeleteModel(
            name='FieldTypeModels',
        ),
    ]
