# Generated by Django 3.2.9 on 2022-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0022_auto_20220301_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltestmodel',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
