# Generated by Django 3.2.9 on 2021-12-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0023_jobstatusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='jobProgressStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_progress_status', to='RecruitmentManagementApp.jobstatusmodel'),
        ),
    ]
