# Generated by Django 3.2.9 on 2022-03-01 11:24

import RecruitmentManagementApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0023_practicaltestmodel_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='digitalSignature',
            field=models.ImageField(upload_to=RecruitmentManagementApp.models.image_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='hscCertificate',
            field=models.FileField(upload_to=RecruitmentManagementApp.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='passportSizePhoto',
            field=models.ImageField(upload_to=RecruitmentManagementApp.models.image_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='sscCertificate',
            field=models.FileField(upload_to=RecruitmentManagementApp.models.content_file_name),
        ),
    ]
