# Generated by Django 3.2.9 on 2021-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0024_alter_userjobappliedmodel_jobprogressstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatusmodel',
            name='statusOrder',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
