# Generated by Django 3.2.9 on 2021-12-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0025_jobstatusmodel_statusorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjobappliedmodel',
            old_name='appliedTime',
            new_name='appliedDate',
        ),
    ]
