# Generated by Django 3.2.9 on 2022-03-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0028_alter_signedappointmentlettermodel_appointmentletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobappliedmodel',
            name='appliedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
