# Generated by Django 3.2.9 on 2022-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0029_alter_userjobappliedmodel_applieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='jobType',
            field=models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('internship', 'Internship'), ('freelancing', 'Freelancing')], max_length=50, verbose_name='job type'),
        ),
    ]
