# Generated by Django 3.2.9 on 2022-03-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0030_alter_jobpostmodel_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
