# Generated by Django 3.2.9 on 2022-03-07 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0032_alter_referenceinformationmodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='phoneNumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
