# Generated by Django 3.2.9 on 2022-03-07 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0034_alter_referenceinformationmodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='phoneNumber',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
