# Generated by Django 3.2.9 on 2022-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0036_auto_20220307_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
