# Generated by Django 3.2.9 on 2022-03-07 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0037_alter_referenceinformationmodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(whitelist=['gmail.com', 'yahoo.com', 'hotmail.com'])]),
        ),
    ]
