# Generated by Django 3.2.9 on 2022-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0038_alter_referenceinformationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
