# Generated by Django 3.2.9 on 2022-03-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0040_candidatejoiningfeedbackmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejoiningfeedbackmodel',
            name='applicationId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_joining_feedback_application_id', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
