# Generated by Django 3.2.9 on 2022-03-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0041_alter_candidatejoiningfeedbackmodel_applicationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejoiningfeedbackmodel',
            name='allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RefereeInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('name_of_company', models.CharField(max_length=255)),
                ('address_of_company', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_confirmation_email', to='RecruitmentManagementApp.userjobappliedmodel')),
            ],
        ),
    ]
