# Generated by Django 3.2.9 on 2022-03-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0043_auto_20220310_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeinformationmodel',
            name='reference_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_information_reference', to='RecruitmentManagementApp.referenceinformationmodel'),
            preserve_default=False,
        ),
    ]
