# Generated by Django 3.2.9 on 2022-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0044_refereeinformationmodel_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refereeinformationmodel',
            name='application_id',
        ),
        migrations.AddField(
            model_name='referenceinformationmodel',
            name='slug_field',
            field=models.SlugField(default='sdfds', max_length=255),
            preserve_default=False,
        ),
    ]
