# Generated by Django 3.2.9 on 2022-03-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0046_alter_referenceinformationmodel_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesquestionresponsemodel',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_referee_information', to='RecruitmentManagementApp.refereeinformationmodel'),
        ),
    ]
