# Generated by Django 3.2.9 on 2022-03-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0047_alter_referencesquestionresponsemodel_referee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefereeInformationModel',
            new_name='ReferenceResponseInformationView',
        ),
    ]
