# Generated by Django 3.2.9 on 2022-03-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0049_referenceresponseinformationview_res_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplyfilterquestionmodel',
            name='fieldType',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Radio'), (3, 'Custom'), (4, 'Level Radio')], max_length=50),
        ),
    ]
