# Generated by Django 3.2.9 on 2022-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0050_alter_jobapplyfilterquestionmodel_fieldtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceinformationmodel',
            name='ref_response',
            field=models.BooleanField(default=False),
        ),
    ]
