# Generated by Django 3.2.9 on 2022-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0051_referenceinformationmodel_ref_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentsmodel',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officialdocumentsmodel',
            name='appointmentLetter',
            field=models.TextField(blank=True),
        ),
    ]
