# Generated by Django 3.2.9 on 2022-03-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0052_auto_20220311_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialdocumentsmodel',
            name='is_generated',
        ),
        migrations.AddField(
            model_name='officialdocumentsmodel',
            name='allow_applicant_access',
            field=models.BooleanField(default=False),
        ),
    ]
