# Generated by Django 3.2.9 on 2022-03-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0055_officialdocumentsmodel_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentsmodel',
            name='applicationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_documents_application_id', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
