# Generated by Django 3.2.9 on 2022-03-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0058_alter_referenceinformationmodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
