# Generated by Django 3.2.9 on 2022-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0059_alter_referenceinformationmodel_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmissionmodel',
            name='update_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
