# Generated by Django 3.2.9 on 2022-04-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0060_documentsubmissionmodel_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceinformationmodel',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
