# Generated by Django 3.2.9 on 2022-04-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0062_policysentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicySentModel',
        ),
    ]
