# Generated by Django 3.2.9 on 2022-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0063_delete_policysentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
