# Generated by Django 3.2.9 on 2021-11-23 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldType', models.CharField(max_length=50, verbose_name='Field Type')),
            ],
            options={
                'verbose_name_plural': 'Field Type',
            },
        ),
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=50, verbose_name='Level')),
            ],
            options={
                'verbose_name_plural': 'Questions Level',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qusAnswer', models.CharField(max_length=255, verbose_name='Question Answer')),
            ],
            options={
                'verbose_name_plural': 'Question Answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='UserApp.userdepartmentmodel')),
                ('fieldType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_field_type', to='QuizApp.fieldtypemodels')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_level', to='QuizApp.levelmodel')),
            ],
            options={
                'verbose_name_plural': 'Question Set',
            },
        ),
        migrations.CreateModel(
            name='SubmittedAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenAnswer', models.CharField(max_length=255, null=True)),
                ('correctAnswer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='QuizApp.questionanswermodel')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_question', to='QuizApp.questionsetmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Submitted Answer',
            },
        ),
        migrations.AddField(
            model_name='questionanswermodel',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='QuizApp.questionsetmodel'),
        ),
    ]
