# Generated by Django 3.2.9 on 2021-12-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldType', models.CharField(max_length=50, verbose_name='Field Type')),
            ],
            options={
                'verbose_name_plural': 'Field Type',
            },
        ),
        migrations.CreateModel(
            name='JobApplyFilterQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='filter_question')),
            ],
            options={
                'verbose_name_plural': 'Filter Question List',
            },
        ),
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=50, verbose_name='Level')),
            ],
            options={
                'verbose_name_plural': 'Questions Level',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qusAnswer', models.CharField(max_length=255, verbose_name='Question Answer')),
            ],
            options={
                'verbose_name_plural': 'Question Answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
            ],
            options={
                'verbose_name_plural': 'Question Set',
            },
        ),
        migrations.CreateModel(
            name='SubmittedAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenAnswer', models.CharField(max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_question', to='QuizApp.questionsetmodel')),
            ],
            options={
                'verbose_name_plural': 'Submitted Answer',
            },
        ),
    ]
