# Generated by Django 3.2.9 on 2021-12-14 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
        ('QuizApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedanswermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsetmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_name', to='UserApp.userdepartmentmodel'),
        ),
        migrations.AddField(
            model_name='questionsetmodel',
            name='fieldType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_field_type', to='QuizApp.fieldtypemodels'),
        ),
        migrations.AddField(
            model_name='questionsetmodel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_level', to='QuizApp.levelmodel'),
        ),
        migrations.AddField(
            model_name='questionanswermodel',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='QuizApp.questionsetmodel'),
        ),
        migrations.AddField(
            model_name='jobapplyfilterquestionmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_department_name', to='UserApp.userdepartmentmodel'),
        ),
        migrations.AddField(
            model_name='jobapplyfilterquestionmodel',
            name='fieldType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_question_field_type', to='QuizApp.fieldtypemodels'),
        ),
    ]
