# Generated by Django 3.2.9 on 2021-11-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_author', to='UserApp.user'),
            preserve_default=False,
        ),
    ]
