# Generated by Django 3.2.9 on 2022-01-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterQuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_apply_filter_question_answer', to='QuizApp.jobapplyfilterquestionmodel')),
            ],
        ),
    ]
