# Generated by Django 3.2.9 on 2022-01-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_filterquestionanswermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterquestionanswermodel',
            old_name='question',
            new_name='filterQuestion',
        ),
    ]
