# Generated by Django 3.2.9 on 2022-01-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_rename_question_filterquestionanswermodel_filterquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterquestionanswermodel',
            old_name='filterQuestion',
            new_name='question',
        ),
    ]
