# Generated by Django 3.2.9 on 2021-11-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_questionsetmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsetmodel',
            name='author',
        ),
    ]
