# Generated by Django 3.2.9 on 2021-11-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_remove_questionsetmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswermodel',
            name='correctAnswer',
        ),
    ]
