# Generated by Django 3.2.9 on 2022-02-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_rename_filterquestion_filterquestionanswermodel_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterquestionanswermodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='jobapplyfilterquestionmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobapplyfilterquestionmodel',
            name='fieldType',
        ),
        migrations.RemoveField(
            model_name='questionanswermodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionsetmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='questionsetmodel',
            name='fieldType',
        ),
        migrations.RemoveField(
            model_name='questionsetmodel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='submittedanswermodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='submittedanswermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='FieldTypeModels',
        ),
        migrations.DeleteModel(
            name='FilterQuestionAnswerModel',
        ),
    ]
