# Generated by Django 3.2.9 on 2022-02-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_auto_20220207_1443'),
        ('RecruitmentManagementApp', '0013_auto_20220207_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplyFilterQuestionModel',
        ),
        migrations.DeleteModel(
            name='LevelModel',
        ),
        migrations.DeleteModel(
            name='QuestionAnswerModel',
        ),
        migrations.DeleteModel(
            name='QuestionSetModel',
        ),
        migrations.DeleteModel(
            name='SubmittedAnswerModel',
        ),
    ]
