# Generated by Django 3.2.9 on 2021-11-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0011_remove_submittedanswermodel_correctanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedanswermodel',
            name='correctAnswer',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='QuizApp.questionanswermodel'),
            preserve_default=False,
        ),
    ]
