# Generated by Django 3.2.9 on 2021-11-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0013_remove_submittedanswermodel_correctanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedanswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_question', to='QuizApp.questionanswermodel'),
        ),
    ]
