# Generated by Django 3.2.9 on 2021-11-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0016_submittedanswermodel_correctanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedanswermodel',
            name='correctAnswer',
        ),
    ]
