# Generated by Django 3.2.9 on 2021-11-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
        ('QuizApp', '0017_remove_submittedanswermodel_correctanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplyFilterQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='filter_question')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_department_name', to='UserApp.userdepartmentmodel')),
                ('fieldType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_question_field_type', to='QuizApp.fieldtypemodels')),
            ],
            options={
                'verbose_name_plural': 'Filter Question List',
            },
        ),
    ]
