# Generated by Django 3.2.9 on 2021-11-25 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuizApp', '0019_filterquestionsresponsemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterquestionsresponsemodel',
            name='user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='response_by', to='UserApp.user'),
            preserve_default=False,
        ),
    ]
