# Generated by Django 3.2.9 on 2021-12-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0020_filterquestionsresponsemodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterQuestionsResponseModel',
        ),
    ]
