# Generated by Django 3.2.9 on 2021-11-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('lastDate', models.DateField()),
                ('startDate', models.TimeField()),
                ('endDate', models.TimeField()),
                ('level', models.CharField(max_length=255, null=True)),
                ('shift', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('vacancies', models.IntegerField()),
                ('jobDescription', models.CharField(max_length=255)),
                ('uploadCV', models.FileField(upload_to='user/')),
            ],
        ),
        migrations.CreateModel(
            name='UserJobAppliedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='HrManagementApp.jobpostmodel')),
            ],
        ),
    ]
