# Generated by Django 3.2.9 on 2021-11-21 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('lastDate', models.DateField()),
                ('startDate', models.TimeField()),
                ('endDate', models.TimeField()),
                ('level', models.CharField(max_length=255, null=True)),
                ('shift', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('vacancies', models.IntegerField()),
                ('jobDescription', models.CharField(max_length=255)),
                ('uploadCV', models.FileField(upload_to='user/')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_jobPost', to='UserApp.userdepartmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserJobAppliedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='HrManagementApp.jobpostmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
