# Generated by Django 3.2.9 on 2021-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HrManagementApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostmodel',
            old_name='lastDate',
            new_name='lastDateOfApply',
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='jobTitle',
            field=models.CharField(max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='location',
            field=models.CharField(max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='startDate',
            field=models.DateField(),
        ),
    ]
