# Generated by Django 3.2.9 on 2021-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designate if the user has Admin status', verbose_name='Admin Status'),
        ),
    ]
