# Generated by Django 3.2.9 on 2021-11-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0003_auto_20211116_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, help_text='Designate if the user has Hr status', verbose_name='Hr Status'),
        ),
    ]
