# Generated by Django 3.2.9 on 2021-11-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0004_alter_user_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='Designate if the user has Employee status', verbose_name='Employee Status'),
        ),
    ]
