# Generated by Django 3.2.9 on 2021-11-16 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0005_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=20, verbose_name='Choose Gender')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='Authentication_App.userdepartmentmodel')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_designation', to='Authentication_App.userdepartmentmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
