# Generated by Django 3.2.9 on 2021-11-16 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0006_userdepartmentmodel_userdesignationmodel_userinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartmentmodel',
            name='deptManager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
