# Generated by Django 3.2.9 on 2021-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0007_userdepartmentmodel_deptmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdepartmentmodel',
            options={'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='userdesignationmodel',
            options={'verbose_name_plural': 'Designation'},
        ),
        migrations.AlterModelOptions(
            name='userinfomodel',
            options={'verbose_name_plural': 'Designation'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False, help_text='Designate if the user has Candidate status', verbose_name='Employee Status'),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=20, verbose_name='Choose Shift'),
        ),
    ]
