# Generated by Django 3.2.9 on 2022-02-11 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0018_alter_useracademicinfomodel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalEmail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('joiningDate', models.DateField(blank=True)),
                ('designation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation', to='UserApp.userdesignationmodel')),
                ('empDepartment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='UserApp.userdepartmentmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=255)),
                ('projectDescription', models.TextField(blank=True)),
                ('projectStatus', models.CharField(blank=True, choices=[('new', 'new'), ('on_progress', 'On Progress'), ('finished', 'Finished')], max_length=50)),
                ('projectDeadline', models.DateField(blank=True)),
                ('projectAssignTo', models.ManyToManyField(related_name='project_assign_to_employee', to='HRM_Admin.EmployeeInformationModel')),
                ('projectManager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_employee', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(blank=True, max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_employee', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
