# Generated by Django 3.2.9 on 2022-02-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmergencyContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.CharField(blank=True, max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_emergency_contact_info', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.CharField(max_length=100)),
                ('accountName', models.CharField(blank=True, max_length=255)),
                ('bankName', models.CharField(blank=True, max_length=255)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank_info', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
