# Generated by Django 3.2.9 on 2022-02-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0002_employeebankinfomodel_employeeemergencycontactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebankinfomodel',
            old_name='accountName',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='employeebankinfomodel',
            old_name='bankName',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='employeeinformationmodel',
            old_name='empDepartment',
            new_name='emp_department',
        ),
        migrations.RenameField(
            model_name='employeeinformationmodel',
            old_name='joiningDate',
            new_name='joining_date',
        ),
        migrations.RenameField(
            model_name='employeeinformationmodel',
            old_name='personalEmail',
            new_name='personal_email',
        ),
        migrations.RenameField(
            model_name='projectinformationmodel',
            old_name='projectAssignTo',
            new_name='project_assignTo',
        ),
        migrations.RenameField(
            model_name='projectinformationmodel',
            old_name='projectDeadline',
            new_name='project_deadline',
        ),
        migrations.RenameField(
            model_name='projectinformationmodel',
            old_name='projectDescription',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='projectinformationmodel',
            old_name='projectManager',
            new_name='project_manager',
        ),
        migrations.RenameField(
            model_name='projectinformationmodel',
            old_name='projectStatus',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='projectinformationmodel',
            old_name='projectTitle',
            new_name='project_title',
        ),
    ]
