# Generated by Django 3.2.9 on 2022-02-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0003_auto_20220211_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebankinfomodel',
            old_name='accountNo',
            new_name='account_no',
        ),
    ]
