# Generated by Django 3.2.9 on 2022-02-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_alter_useracademicinfomodel_options'),
        ('HRM_Admin', '0007_modulepermissionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=255)),
                ('training_link', models.URLField()),
                ('training_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_department', to='UserApp.userdepartmentmodel')),
            ],
        ),
    ]
