# Generated by Django 3.2.9 on 2022-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0009_auto_20220217_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformationmodel',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('roster', 'Roster')], default='day', max_length=200),
            preserve_default=False,
        ),
    ]
