# Generated by Django 3.2.9 on 2022-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0010_employeeinformationmodel_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformationmodel',
            name='employee_is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
