# Generated by Django 3.2.9 on 2022-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0011_employeeinformationmodel_employee_is_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodel',
            name='training_link',
            field=models.URLField(blank=True),
        ),
    ]
