# Generated by Django 3.2.9 on 2022-02-25 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0012_alter_trainingmodel_training_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='assign_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
