# Generated by Django 3.2.9 on 2022-02-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0013_trainingmodel_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarymodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_employee', to='HRM_Admin.employeeinformationmodel'),
        ),
    ]
