# Generated by Django 3.2.9 on 2022-03-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0014_alter_employeesalarymodel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankinfomodel',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
