# Generated by Django 3.2.9 on 2022-10-14 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0032_delete_resignationmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRM_Admin', '0016_employeeinformationmodel_personal_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidInvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_name', models.FileField(upload_to='paid_invoices')),
                ('Created_date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('uploaded_by', models.CharField(choices=[('hr', 'HR'), ('gm', 'GM'), ('ceo', 'CEO'), ('pm', 'PM')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('month', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('purchase_type', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash')], max_length=200)),
                ('expanse_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WarrentyListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('warranty_end', models.DateField()),
                ('warranty_file', models.FileField(upload_to='warranty_items')),
                ('uploaded_by', models.CharField(choices=[('hr', 'HR'), ('gm', 'GM'), ('ceo', 'CEO'), ('pm', 'PM')], max_length=100)),
                ('item_category', models.CharField(max_length=200)),
                ('expense_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewSalarySheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid_in', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_employee_sheet', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalarySheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('roster', 'Roster')], max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('paid_in', models.DateField()),
                ('absent', models.IntegerField(default=0)),
                ('total_late_hours', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_designation_sheet', to='UserApp.userdesignationmodel')),
                ('emp_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_department_sheet', to='UserApp.userdepartmentmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
