# Generated by Django 3.2.9 on 2021-11-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_job_post_permission',
            new_name='is_hr',
        ),
    ]
