# Generated by Django 3.2.9 on 2021-12-29 08:34

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, verbose_name='Choose Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Size Recommended: 512x512', keep_meta=True, quality=100, size=[512, 512], upload_to='users/'),
        ),
    ]
