# Generated by Django 3.2.9 on 2021-12-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfomodel',
            name='userSkills',
        ),
        migrations.AddField(
            model_name='employeeinfomodel',
            name='personalEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
