# Generated by Django 3.2.9 on 2021-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_is_job_post_permission_user_is_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=True, help_text='Designate if the user has Candidate status', verbose_name='candidate Status'),
        ),
    ]
