# Generated by Django 3.2.9 on 2021-11-20 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademicinfomodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
