# Generated by Django 3.2.9 on 2021-12-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20211229_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfomodel',
            old_name='personalEmail',
            new_name='email',
        ),
    ]
