# Generated by Django 3.2.9 on 2021-12-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_userdepartmentmodel_deptmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceinformationmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='DocumentSubmissionModel',
        ),
        migrations.DeleteModel(
            name='ReferenceInformationModel',
        ),
    ]
