# Generated by Django 3.2.9 on 2021-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_is_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, help_text='Designate if the user has HR status', verbose_name='HR Status'),
        ),
    ]
