# Generated by Django 3.2.9 on 2021-12-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20211226_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmissionmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
