# Generated by Django 3.2.9 on 2021-11-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_useracademicinfomodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracademicinfomodel',
            name='major',
        ),
    ]
