# Generated by Django 3.2.9 on 2021-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20211128_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademicinfomodel',
            name='year',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
