# Generated by Django 3.2.9 on 2021-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_useracademicinfomodel_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'User skills',
            },
        ),
    ]
