# Generated by Django 3.2.9 on 2021-12-27 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20211226_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ManyToManyField(to='UserApp.SkillsModel', verbose_name='user_skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_user', to=settings.AUTH_USER_MODEL, verbose_name='skills_user')),
            ],
        ),
    ]
