# Generated by Django 3.2.9 on 2021-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_skillsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='users/default.png', upload_to='users/'),
        ),
    ]
