# Generated by Django 3.2.9 on 2021-12-27 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userskillsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userskillsmodel',
            options={'verbose_name_plural': 'User Skills'},
        ),
        migrations.AlterField(
            model_name='userskillsmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
