# Generated by Django 3.2.9 on 2021-11-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_remove_useracademicinfomodel_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracademicinfomodel',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='useracademicinfomodel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='useracademicinfomodel',
            name='year',
        ),
    ]
