# Generated by Django 3.2.9 on 2021-11-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_useracademicinfomodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracademicinfomodel',
            name='year',
        ),
    ]
