# Generated by Django 3.2.9 on 2021-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_remove_useracademicinfomodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracademicinfomodel',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
