# Generated by Django 3.2.9 on 2022-01-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_grouporsubjectmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsmodel',
            options={'verbose_name_plural': 'skills'},
        ),
    ]
