# Generated by Django 3.2.9 on 2022-01-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_skillsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademicinfomodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
