# Generated by Django 3.2.9 on 2021-12-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_auto_20211208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
