# Generated by Django 3.2.9 on 2021-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrainingexperiencemodel',
            old_name='duration',
            new_name='completeDate',
        ),
        migrations.AddField(
            model_name='usertrainingexperiencemodel',
            name='startDate',
            field=models.IntegerField(default=0.08333333333333333),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
