# Generated by Django 3.2.9 on 2022-01-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_useracademicinfomodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracademicinfomodel',
            name='year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
