# Generated by Django 3.2.9 on 2021-12-09 05:18

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_documentsubmissionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='graduationCertificate',
            field=models.FileField(upload_to=UserApp.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='hscCertificate',
            field=models.FileField(upload_to=UserApp.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='nidCard',
            field=models.FileField(blank=True, upload_to=UserApp.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='postGraduationCertificate',
            field=models.FileField(blank=True, upload_to=UserApp.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='sscCertificate',
            field=models.FileField(upload_to=UserApp.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmodel',
            name='userPassportImage',
            field=models.ImageField(upload_to=UserApp.models.image_file_name),
        ),
    ]
