# Generated by Django 3.2.9 on 2021-12-09 06:52

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_referenceinformationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceinformationmodel',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to=UserApp.models.content_file_name),
        ),
    ]
