# Generated by Django 3.2.9 on 2022-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_usertrainingexperiencemodel_certificateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingexperiencemodel',
            name='courseDuration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userworkingexperiencemodel',
            name='jobAchievement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertrainingexperiencemodel',
            name='completeDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertrainingexperiencemodel',
            name='startDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userworkingexperiencemodel',
            name='responsibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
