# Generated by Django 3.2.9 on 2022-02-09 04:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20220207_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format='JPEG', help_text='Size Recommended: 512x512', keep_meta=True, quality=100, size=[512, 512], upload_to='users/'),
        ),
    ]
