# Generated by Django 3.2.9 on 2021-12-12 09:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0016_alter_referenceinformationmodel_attachedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Size Recommended: 512x512', keep_meta=True, quality=100, size=[512, 512], upload_to='users/'),
        ),
    ]
