# Generated by Django 3.2.9 on 2022-02-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_alter_user_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useracademicinfomodel',
            options={'ordering': ['year'], 'verbose_name_plural': 'Academic Information'},
        ),
    ]
