# Generated by Django 3.2.9 on 2022-02-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_alter_useracademicinfomodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfomodel',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Roster', 'Roster')], max_length=20, verbose_name='Choose Shift'),
        ),
    ]
