# Generated by Django 3.2.9 on 2022-03-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_alter_employeeinfomodel_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInfoModel',
        ),
    ]
