# Generated by Django 3.2.9 on 2022-03-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_delete_employeeinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerObjectiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_objective_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
