# Generated by Django 3.2.9 on 2022-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_careerobjectivemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercertificationsmodel',
            name='dateOfExpiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercertificationsmodel',
            name='dateOfAchievement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
