# Generated by Django 3.2.9 on 2022-03-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0024_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesignationmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_department', to='UserApp.userdepartmentmodel'),
        ),
    ]
