# Generated by Django 3.2.9 on 2022-04-19 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0030_alter_user_signature_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resignationDate', models.DateField()),
                ('noticeDate', models.DateField()),
                ('resignationstaus', models.BooleanField(default=False)),
                ('resignatioAcceptDate', models.DateField(blank=True, null=True)),
                ('exitInterview', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resignation',
            },
        ),
    ]
