# Generated by Django 3.2.9 on 2022-04-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0031_resignationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResignationModel',
        ),
    ]
