# Generated by Django 3.2.9 on 2022-02-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRM_Admin', '0009_auto_20220217_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTrainingResponseResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_mark', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_test_result_user', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_training_response', to='HRM_Admin.trainingmodel')),
            ],
        ),
    ]
