# Generated by Django 3.2.9 on 2022-02-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0011_employeeinformationmodel_employee_is_permanent'),
        ('HRM_User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('maternity', 'Maternity Leave'), ('wedding', 'Wedding Leave'), ('sick', 'Sick Leave')], max_length=255)),
                ('leave_from', models.DateField()),
                ('leave_to', models.DateField()),
                ('no_of_days', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM_Admin.employeeinformationmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_employee', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
