# Generated by Django 3.2.9 on 2022-04-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0016_employeeinformationmodel_personal_email'),
        ('HRM_User', '0004_resignationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_employee', to='HRM_Admin.employeeinformationmodel'),
        ),
    ]
