# Generated by Django 3.2.9 on 2022-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0004_resignationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='resignationstaus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
