# Generated by Django 3.2.9 on 2022-04-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0005_alter_resignationmodel_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resignationmodel',
            options={},
        ),
    ]
