# Generated by Django 3.2.9 on 2022-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0006_alter_resignationmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignationmodel',
            name='exitInterview',
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='resignationDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
