# Generated by Django 3.2.9 on 2022-04-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0006_alter_resignationmodel_resignationstaus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignationmodel',
            name='resignationstaus',
        ),
    ]
