# Generated by Django 3.2.9 on 2022-04-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0007_remove_resignationmodel_resignationstaus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='resignationstaus',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
