# Generated by Django 3.2.9 on 2022-04-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0008_resignationmodel_resignationstaus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('bool', 'Bool')], default='text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExitInterviewAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='HRM_User.exitinterviewquestionmodel')),
                ('resignation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_employee', to='HRM_User.resignationmodel')),
            ],
        ),
    ]
