# Generated by Django 3.2.9 on 2022-04-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0009_exitinterviewanswermodel_exitinterviewquestionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitinterviewanswermodel',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
