# Generated by Django 3.2.9 on 2022-04-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_User', '0010_exitinterviewanswermodel_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitinterviewanswermodel',
            name='ok',
        ),
    ]
