# Generated by Django 3.2.9 on 2022-01-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0002_supportmessagemodel_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessagemodel',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_support_ticket', to='SupportApp.ticketingforsupportmodel'),
        ),
    ]
