# Generated by Django 3.2.9 on 2022-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0003_alter_supportmessagemodel_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessagemodel',
            name='id_read',
        ),
        migrations.AddField(
            model_name='supportmessagemodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
