# Generated by Django 3.2.9 on 2022-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0005_supportmessagemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingforsupportmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
