# Generated by Django 3.2.9 on 2022-02-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0007_auto_20220202_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketingforsupportmodel',
            name='query',
        ),
        migrations.AddField(
            model_name='ticketingforsupportmodel',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_support_service', to='SupportApp.servicemodel'),
            preserve_default=False,
        ),
    ]
