# Generated by Django 3.2.9 on 2022-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0008_auto_20220202_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketingforsupportmodel',
            name='service',
        ),
        migrations.AddField(
            model_name='ticketingforsupportmodel',
            name='query',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
