# Generated by Django 3.2.9 on 2022-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0012_alter_supportmessagemodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessagemodel',
            name='userImage',
            field=models.TextField(blank=True),
        ),
    ]
