# Generated by Django 3.2.9 on 2022-02-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportApp', '0013_alter_supportmessagemodel_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingforsupportmodel',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supportmessagemodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketingforsupportmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
