# Generated by Django 3.2.9 on 2021-12-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTestUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practicalTestInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_info', to='RecruitmentManagementApp.practicaltestmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
