# Generated by Django 3.2.9 on 2022-03-03 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecruitmentManagementApp', '0001_initial'),
        ('UserApp', '0019_alter_employeeinfomodel_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminOperationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltestusermodel',
            name='practicalTestInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_info', to='RecruitmentManagementApp.practicaltestmodel'),
        ),
        migrations.AddField(
            model_name='practicaltestusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicaltestmarkinputmodel',
            name='jobApplication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_application', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AddField(
            model_name='practicaltestmarkinputmodel',
            name='markAssignBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_assigned_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='appliedJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_user_applied_model', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_during_interview_candidate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_during_interview_interviewer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='applicationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_id_applied_job', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewer_designation', to='UserApp.userdesignationmodel'),
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='scheduleBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_scheduled_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generateappointmentlettermodel',
            name='applicationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_id_job_applied_user', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AddField(
            model_name='finalsalarynegotiationmodel',
            name='assignedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalsalarynegotiationmodel',
            name='jobApplication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_final_salary', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AddField(
            model_name='commentsondocumentsmodel',
            name='applicationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents_comment', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
