# Generated by Django 3.2.9 on 2021-12-28 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminOperationApp', '0002_practicaltestusermodel_practicaltestinfo'),
        ('RecruitmentManagementApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practicaltestusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='appliedJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job_user_applied_model', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_during_interview_interviewer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_during_interview_candidate_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
