# Generated by Django 3.2.9 on 2022-01-01 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminOperationApp', '0004_rename_user_markingduringinterviewmodel_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTestMarkInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testMark', models.CharField(blank=True, choices=[('5', 'A'), ('4', 'B'), ('3', 'C'), ('2', 'D'), ('1', 'E'), ('0', 'F')], max_length=2, null=True)),
                ('jobApplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_application', to='RecruitmentManagementApp.userjobappliedmodel')),
                ('markAssignBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_assigned_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
