# Generated by Django 3.2.9 on 2022-01-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0002_initial'),
        ('AdminOperationApp', '0005_practicaltestmarkinputmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicaltestmarkinputmodel',
            name='jobApplication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_test_application', to='RecruitmentManagementApp.userjobappliedmodel'),
        ),
    ]
