# Generated by Django 3.2.9 on 2022-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminOperationApp', '0007_meetingschedulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingschedulemodel',
            name='meetingLocation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
