# Generated by Django 3.2.9 on 2022-01-06 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0002_initial'),
        ('AdminOperationApp', '0008_meetingschedulemodel_meetinglocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingScheduleModel',
            new_name='InterviewTimeScheduleModel',
        ),
    ]
