# Generated by Django 3.2.9 on 2022-01-07 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminOperationApp', '0009_rename_meetingschedulemodel_interviewtimeschedulemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtimeschedulemodel',
            name='meetingHost',
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='meetingHost',
            field=models.ManyToManyField(null=True, related_name='meeting_host_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
