# Generated by Django 3.2.9 on 2022-01-07 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminOperationApp', '0010_auto_20220107_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtimeschedulemodel',
            name='meetingHost',
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='meetingHost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_host_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
