# Generated by Django 3.2.9 on 2022-01-07 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_alter_useracademicinfomodel_year'),
        ('AdminOperationApp', '0011_auto_20220107_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewtimeschedulemodel',
            name='meetingHost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_host_designation', to='UserApp.userdesignationmodel'),
        ),
    ]
