# Generated by Django 3.2.9 on 2022-01-13 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_userworkingexperiencemodel_quitdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminOperationApp', '0012_alter_interviewtimeschedulemodel_meetinghost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewtimeschedulemodel',
            old_name='meetingScheduleBy',
            new_name='scheduleBy',
        ),
        migrations.RemoveField(
            model_name='interviewtimeschedulemodel',
            name='meetingDateTime',
        ),
        migrations.RemoveField(
            model_name='interviewtimeschedulemodel',
            name='meetingGuest',
        ),
        migrations.RemoveField(
            model_name='interviewtimeschedulemodel',
            name='meetingHost',
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_interview_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='interviewDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='interviewTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewer_designation', to='UserApp.userdesignationmodel'),
        ),
    ]
