# Generated by Django 3.2.9 on 2022-01-17 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0004_auto_20220107_1621'),
        ('AdminOperationApp', '0015_auto_20220113_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateAppointmentLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectLine', models.CharField(blank=True, max_length=255)),
                ('joiningDate', models.DateField()),
                ('grossSalary', models.IntegerField()),
                ('jobDescription', models.TextField()),
                ('termsCondition', models.TextField()),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_id_job_applied_user', to='RecruitmentManagementApp.userjobappliedmodel')),
            ],
        ),
    ]
