# Generated by Django 3.2.9 on 2022-01-21 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminOperationApp', '0017_alter_interviewtimeschedulemodel_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='behavior',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='dressSense',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='eagerness',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='engSpeaking',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='flexibility',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='personality',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='professionalism',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markingduringinterviewmodel',
            name='technicalKnowledge',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='practicaltestmarkinputmodel',
            name='testMark',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='FinalSalaryNegotiationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
