# Generated by Django 3.2.9 on 2022-01-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0004_auto_20220107_1621'),
        ('AdminOperationApp', '0018_auto_20220121_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsalarynegotiationmodel',
            name='finalSalary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalsalarynegotiationmodel',
            name='jobApplication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_application_final_salary', to='RecruitmentManagementApp.userjobappliedmodel'),
            preserve_default=False,
        ),
    ]
