# Generated by Django 3.2.9 on 2022-02-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0004_auto_20220107_1621'),
        ('AdminOperationApp', '0019_auto_20220124_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsOnDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents_comment', to='RecruitmentManagementApp.userjobappliedmodel')),
            ],
        ),
    ]
