# Generated by Django 3.2.9 on 2022-03-02 04:19

import AdminOperationApp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecruitmentManagementApp', '0024_auto_20220301_1724'),
        ('AdminOperationApp', '0022_auto_20220203_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedAppointmentLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentLetter', models.FileField(upload_to=AdminOperationApp.models.doc_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('applicationId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_appointment_letter_application_id', to='RecruitmentManagementApp.userjobappliedmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signed_appointment_letter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
