# Generated by Django 3.2.9 on 2022-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminOperationApp', '0024_delete_signedappointmentlettermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtimeschedulemodel',
            name='candidate',
        ),
        migrations.AddField(
            model_name='interviewtimeschedulemodel',
            name='interviewLocationType',
            field=models.CharField(blank=True, choices=[('office', 'Office'), ('online', 'Online')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewtimeschedulemodel',
            name='interviewLocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
