# Generated by Django 3.2.9 on 2022-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminOperationApp', '0025_auto_20220303_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewtimeschedulemodel',
            name='interviewLocationType',
            field=models.CharField(choices=[('office', 'Office'), ('virtual', 'Virtual')], default='office', max_length=50),
        ),
    ]
