# Generated by Django 3.2.9 on 2022-04-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminOperationApp', '0028_alter_interviewtimeschedulemodel_interviewtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingduringinterviewmodel',
            name='docsPermission',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
