# Generated by Django 3.2.9 on 2022-04-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentManagementApp', '0063_delete_policysentmodel'),
        ('AdminOperationApp', '0029_markingduringinterviewmodel_docspermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicySentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_sent_application_id', to='RecruitmentManagementApp.userjobappliedmodel')),
            ],
        ),
    ]
