# Generated by Django 3.2.9 on 2022-02-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRM_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCriteriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyuserresponsemodel',
            name='months',
        ),
        migrations.AlterField(
            model_name='surveyquestionmodel',
            name='answers',
            field=models.ManyToManyField(related_name='questions_answers', to='HRM_controller.SurveyAnswerSheetModel'),
        ),
        migrations.CreateModel(
            name='EmployeeEvaluationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=255)),
                ('ratings', models.CharField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Uncertain'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=255)),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='HRM_controller.employeecriteriamodel')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
