# Generated by Django 3.2.9 on 2022-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionmodel',
            name='answers',
            field=models.ManyToManyField(related_name='questions_answers', to='HRM_controller.SurveyAnswerSheetModel'),
        ),
    ]
