# Generated by Django 3.2.9 on 2022-02-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0002_auto_20220216_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeevaluationmodel',
            name='months',
        ),
    ]
