# Generated by Django 3.2.9 on 2022-02-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0002_alter_surveyquestionmodel_answers'),
        ('HRM_controller', '0003_remove_employeeevaluationmodel_months'),
    ]

    operations = [
    ]
