# Generated by Django 3.2.9 on 2022-02-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0004_merge_20220216_1902'),
        ('HRM_controller', '0004_merge_20220217_0919'),
    ]

    operations = [
    ]
