# Generated by Django 3.2.9 on 2022-02-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0010_employeeinformationmodel_shift'),
        ('HRM_controller', '0006_announcementmodel_noticemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEmployeeRelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=50, unique=True)),
                ('signature_id', models.CharField(max_length=50, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employee_relation', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
