# Generated by Django 3.2.9 on 2022-02-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0007_attendanceemployeerelmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEmployeeShiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
