# Generated by Django 3.2.9 on 2022-02-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0010_alter_attendanceemployeerelmodel_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceemployeeshiftrelmodel',
            name='employee_relation',
        ),
        migrations.RemoveField(
            model_name='attendanceemployeeshiftrelmodel',
            name='shift',
        ),
        migrations.DeleteModel(
            name='AttendanceEmployeeRelModel',
        ),
        migrations.DeleteModel(
            name='AttendanceEmployeeShiftRelModel',
        ),
    ]
