# Generated by Django 3.2.9 on 2022-02-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0010_employeeinformationmodel_shift'),
        ('HRM_controller', '0022_rename_h_date_holidaymodel_holiday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_reason', models.CharField(max_length=255)),
                ('complain_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('complain_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_employee', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
