# Generated by Django 3.2.9 on 2022-02-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0013_trainingmodel_assign_date'),
        ('HRM_controller', '0023_complainmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_date', models.DateField(blank=True)),
                ('out_time', models.TimeField(blank=True)),
                ('total_hour', models.CharField(blank=True, max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_log', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
