# Generated by Django 3.2.9 on 2022-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0024_employeeattendancelogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendancelogmodel',
            name='reg_id',
            field=models.CharField(default='abc', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
