# Generated by Django 3.2.9 on 2022-03-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0025_employeeattendancelogmodel_reg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeattendancelogmodel',
            name='reg_id',
        ),
    ]
