# Generated by Django 3.2.9 on 2022-03-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0030_alter_attendanceemployeeshiftrelmodel_employee_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attendanceshifttimemodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendanceshifttimemodel',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendanceshifttimemodel',
            name='shift_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM_controller.shifttimemodel'),
        ),
    ]
