# Generated by Django 3.2.9 on 2022-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0032_alter_attendanceshifttimemodel_shift_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendancelogmodel',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendancelogmodel',
            name='out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendancelogmodel',
            name='total_hour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
