# Generated by Django 3.2.9 on 2022-04-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0016_employeeinformationmodel_personal_email'),
        ('HRM_controller', '0033_auto_20220325_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePromotionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_employee', to='HRM_Admin.employeeinformationmodel')),
            ],
        ),
    ]
