# Generated by Django 3.2.9 on 2022-03-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0034_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
