# Generated by Django 3.2.9 on 2022-04-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0027_alter_user_phone_number'),
        ('HRM_controller', '0036_alter_employeepromotionmodel_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepromotionmodel',
            name='employee_designation',
        ),
        migrations.AddField(
            model_name='employeepromotionmodel',
            name='designations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.userdesignationmodel'),
        ),
    ]
