# Generated by Django 3.2.9 on 2022-04-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0027_alter_user_phone_number'),
        ('HRM_controller', '0040_alter_employeepromotionmodel_promotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepromotionmodel',
            name='promotion_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='UserApp.userdesignationmodel'),
        ),
        migrations.AlterField(
            model_name='employeepromotionmodel',
            name='promotion_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='UserApp.userdesignationmodel'),
        ),
    ]
