# Generated by Django 3.2.9 on 2022-04-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0041_auto_20220406_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepromotionmodel',
            name='promotion_from',
        ),
        migrations.AddField(
            model_name='employeepromotionmodel',
            name='promotion_form',
            field=models.CharField(default='Promotion Form', max_length=255),
        ),
    ]
