# Generated by Django 3.2.9 on 2022-04-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0042_auto_20220406_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepromotionmodel',
            name='promotion_form',
            field=models.CharField(max_length=255),
        ),
    ]
