# Generated by Django 3.2.9 on 2022-04-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0043_alter_employeepromotionmodel_promotion_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_form', models.CharField(max_length=255)),
            ],
        ),
    ]
