# Generated by Django 3.2.9 on 2022-04-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0016_employeeinformationmodel_personal_email'),
        ('HRM_controller', '0044_terminationtitlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTerminationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField()),
                ('termination_reason', models.TextField()),
                ('notice_date', models.DateField()),
                ('exit_interview', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_employee', to='HRM_Admin.employeeinformationmodel')),
                ('termination_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_title', to='HRM_controller.terminationtitlemodel')),
            ],
        ),
    ]
