# Generated by Django 3.2.9 on 2022-04-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0045_employeeterminationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminationtitlemodel',
            old_name='termination_form',
            new_name='termination_title',
        ),
        migrations.AlterField(
            model_name='employeeterminationmodel',
            name='termination_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_controller.terminationtitlemodel'),
        ),
    ]
