# Generated by Django 3.2.9 on 2022-04-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_Admin', '0016_employeeinformationmodel_personal_email'),
        ('HRM_controller', '0046_auto_20220406_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepromotionmodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_employee', to='HRM_Admin.employeeinformationmodel'),
        ),
    ]
