# Generated by Django 3.2.9 on 2022-10-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0032_delete_resignationmodel'),
        ('HRM_controller', '0047_alter_employeepromotionmodel_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticemodel',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='surveyquestionmodel',
            name='answers',
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticemodel',
            name='employee',
            field=models.ManyToManyField(related_name='notice_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyquestionmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestionmodel',
            name='department',
            field=models.ManyToManyField(related_name='question_department', to='UserApp.UserDepartmentModel'),
        ),
        migrations.AddField(
            model_name='surveyquestionmodel',
            name='month',
            field=models.CharField(default='October', max_length=255),
        ),
        migrations.AddField(
            model_name='surveyquestionmodel',
            name='year',
            field=models.CharField(default='2022', max_length=255),
        ),
        migrations.AlterField(
            model_name='announcementmodel',
            name='message',
            field=models.TextField(),
        ),
    ]
