# Generated by Django 3.2.9 on 2022-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_controller', '0048_auto_20221014_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaymodel',
            name='month',
            field=models.CharField(default='October', max_length=255),
        ),
    ]
